export enum StatusCertificado {
  EM_ESPERA = 'EM_ESPERA',

  EM_AVALIACAO = 'EM_AVALIACAO',

  APROVADO_PARCIALMENTE = 'APROVADO_PARCIALMENTE',

  CONCLUIDO = 'CONCLUIDO',

  NAO_CONCLUIDO = 'NAO_CONCLUIDO',

  REPROVADO = 'REPROVADO',
}
