export enum TipoAtividade {
  GRUPO_DE_ESTUDOS = 'GRUPO_DE_ESTUDOS',

  PARTICIPACAO_SIMPLES_EM_EVENTOS_PALESTRAS = 'PARTICIPACAO_SIMPLES_EM_EVENTOS_PALESTRAS',

  VOLUNTARIO_NA_ORGANIZACAO_DE_EVENTO_PALESTRA = 'VOLUNTARIO_NA_ORGANIZACAO_DE_EVENTO_PALESTRA',

  PUBLICACAO_DE_ARTIGO_TECNICO_EM_EVENTO_CIENTIFICO = 'PUBLICACAO_DE_ARTIGO_TECNICO_EM_EVENTO_CIENTIFICO',

  APRESENTACAO_PALESTRA_CONVIDADA = 'APRESENTACAO_PALESTRA_CONVIDADA',

  CURSO_MINISTRADO_EM_EVENTO = 'CURSO_MINISTRADO_EM_EVENTO',

  PUBLICACAO_DE_ARTIGO_TECNICO_EM_REVISTA_OU_PERIODICO = 'PUBLICACAO_DE_ARTIGO_TECNICO_EM_REVISTA_OU_PERIODICO',

  MONITORIA = 'MONITORIA',

  PARTICIPACAO_EM_MARATONA_OU_GICANA_DE_PROGRAMACAO = 'PARTICIPACAO_EM_MARATONA_OU_GICANA_DE_PROGRAMACAO',

  ATIVIDADE_TECNICA_EMPRESA_JR = 'ATIVIDADE_TECNICA_EMPRESA_JR',

  PROJETO_DE_EXTENSAO = 'PROJETO_DE_EXTENSAO',

  PROJETO_DE_PESQUISA = 'PROJETO_DE_PESQUISA',

  PROJETO_DE_ENSINO = 'PROJETO_DE_ENSINO',

  ATIVIDADE_DEVISITA_OU_EXCURSAO = 'ATIVIDADE_DEVISITA_OU_EXCURSAO',

  CURSO_PRESENCIAL_OU_A_DISTANCIA = 'CURSO_PRESENCIAL_OU_A_DISTANCIA',

  CONCURSO_DE_EXCELENCIA_EM_TCC = 'CONCURSO_DE_EXCELENCIA_EM_TCC',

  ESTAGIO_NAO_OBRIGATORIO = 'ESTAGIO_NAO_OBRIGATORIO',

  REPRESENTACAO_ESTUDANTIL = 'REPRESENTACAO_ESTUDANTIL',

  ASSISTENCIA_EM_DEFESA_DE_TCC_DISSERTACAO_OU_TESE = 'ASSISTENCIA_EM_DEFESA_DE_TCC_DISSERTACAO_OU_TESE',
}
