package br.com.acc.controle.domain.enumeration;

/**
 * The TipoAtividade enumeration.
 */
public enum TipoAtividade {
    GRUPO_DE_ESTUDOS,
    PARTICIPACAO_SIMPLES_EM_EVENTOS_PALESTRAS,
    VOLUNTARIO_NA_ORGANIZACAO_DE_EVENTO_PALESTRA,
    PUBLICACAO_DE_ARTIGO_TECNICO_EM_EVENTO_CIENTIFICO,
    APRESENTACAO_PALESTRA_CONVIDADA,
    CURSO_MINISTRADO_EM_EVENTO,
    PUBLICACAO_DE_ARTIGO_TECNICO_EM_REVISTA_OU_PERIODICO,
    MONITORIA,
    PARTICIPACAO_EM_MARATONA_OU_GICANA_DE_PROGRAMACAO,
    ATIVIDADE_TECNICA_EMPRESA_JR,
    PROJETO_DE_EXTENSAO,
    PROJETO_DE_PESQUISA,
    PROJETO_DE_ENSINO,
    ATIVIDADE_DEVISITA_OU_EXCURSAO,
    CURSO_PRESENCIAL_OU_A_DISTANCIA,
    CONCURSO_DE_EXCELENCIA_EM_TCC,
    ESTAGIO_NAO_OBRIGATORIO,
    REPRESENTACAO_ESTUDANTIL,
    ASSISTENCIA_EM_DEFESA_DE_TCC_DISSERTACAO_OU_TESE,
}
